FROM debian:buster

RUN apt-get update
RUN apt-get install -y wget maven gnupg2 lsb-release
RUN wget https://download.oracle.com/java/19/archive/jdk-19.0.2_linux-x64_bin.deb -O /jdk.deb
RUN apt-get install -y ./jdk.deb

RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
RUN wget https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add -
RUN apt-get -y update
RUN apt-get install -y postgresql-14
RUN sed -ie 's/local[ ]*all[ ]*postgres[ ]*peer/local all postgres trust/g' /etc/postgresql/14/main/pg_hba.conf

ADD ./target/SHAKAL-BOT-00.jar /SHAKAL-BOT-00.jar
ENTRYPOINT service postgresql start && /usr/lib/jvm/jdk-19/bin/java -jar /SHAKAL-BOT-00.jar
