version: "3.8"

services:
  shakal_bot_db:
    image: shakal-bot-db-image
    container_name: shakal-bot-db
    mem_limit: 50m
    profiles:
      - include
    build:
      context: ./
      dockerfile: ./docker/dbDockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/postgresql/data
    restart: always
    networks:
      internal_network:
        ipv4_address: 172.24.0.2

  shakal_bot_service:
    image: shakal-bot-docker-image
    container_name: shakal-bot-service
    mem_limit: 128m
    profiles:
      - include
    build:
      context: ./
      dockerfile: ./docker/shakalBotServiceDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.3
      internal_network:
        ipv4_address: 172.24.0.3
    depends_on:
      - shakal_bot_db

  water_stuff_bot_service:
    image: water-stuff-bot-image
    container_name: water-stuff-bot-service
    mem_limit: 128m
    profiles:
      - include
    build:
      context: ./
      dockerfile: ./docker/waterStuffBotServiceDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.4
      internal_network:
        ipv4_address: 172.24.0.4
    depends_on:
      - shakal_bot_db

  chat_gpt_bot_service:
    image: chat-gpt-bot-image
    container_name: chat-gpt-bot-service
    mem_limit: 128m
    profiles:
      - exclude
    build:
      context: ./
      dockerfile: ./docker/chatGptServiceDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.5
      internal_network:
        ipv4_address: 172.24.0.5
    depends_on:
      - shakal_bot_db

  crv_bot_service:
    image: crv-bot-image
    container_name: crv-bot-service
    mem_limit: 600m
    profiles:
      - exclude
    build:
      context: ./
      dockerfile: ./docker/crvBotServiceDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.6
      internal_network:
        ipv4_address: 172.24.0.6
    depends_on:
      - shakal_bot_db

  monitoring_bot_service:
    image: monitoring-bot-image
    container_name: monitoring-bot-service
    mem_limit: 256m
    build:
      context: ./
      dockerfile: ./docker/monitoringBotServiceDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.7
      internal_network:
        ipv4_address: 172.24.0.7
    depends_on:
      - shakal_bot_db

  rocket_bot_service:
    image: rocket-bot-docker-image
    container_name: rocket-bot-service
    mem_limit: 128m
    profiles:
      - include
    build:
      context: ./
      dockerfile: ./docker/rocketBotServiceDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.8
      internal_network:
        ipv4_address: 172.24.0.8
    depends_on:
      - shakal_bot_db

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/telegram-data/database
  
  bot_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/telegram-data/bot-files

networks:
  shakal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
  internal_network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
