version: "3.8"

services:
  shakal_bot_db:
    image: shakal-bot-db-image
    container_name: shakal-bot-db
    mem_limit: 50m
    profiles:
      - include
    build:
      context: ./
      dockerfile: docker/databaseDockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/postgresql/data
    restart: always
    networks:
      internal_network:
        ipv4_address: 172.24.0.2

  monitoring_service:
    image: monitoring-service-image
    container_name: monitoring-service
    build:
      context: ./
      dockerfile: docker/monitoringServiceDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.3
      internal_network:
        ipv4_address: 172.24.0.3
    depends_on:
      - shakal_bot_db

  monitoring_telegram_bot:
    image: monitoring-telegram-bot-image
    container_name: monitoring-telegram-bot
    build:
      context: ./
      dockerfile: docker/monitoringTelegramBotDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.4
    depends_on:
      - shakal_bot_db

  shakal_service:
    image: shakal-service-image
    container_name: shakal-service
    profiles:
      - include
    build:
      context: ./
      dockerfile: docker/shakalServiceDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.5
      internal_network:
        ipv4_address: 172.24.0.5
    depends_on:
      - shakal_bot_db

  shakal_telegram_bot:
    image: shakal-telegram-bot-image
    container_name: shakal-telegram-bot
    profiles:
      - include
    build:
      context: ./
      dockerfile: docker/shakalTelegramBotDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.6
    depends_on:
      - shakal_bot_db

  water_stuff_service:
    image: water-stuff-service-image
    container_name: water-stuff-service
    profiles:
      - include
    build:
      context: ./
      dockerfile: docker/waterStuffServiceDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.7
      internal_network:
        ipv4_address: 172.24.0.7
    depends_on:
      - shakal_bot_db

  water_stuff_telegram_bot:
    image: water-stuff-telegram-bot-image
    container_name: water-stuff-telegram-bot
    profiles:
      - include
    build:
      context: ./
      dockerfile: docker/waterStuffTelegramBotDockerfile
    volumes:
      - bot_vol:/bot-files
    restart: always
    networks:
      shakal_network:
        ipv4_address: 172.23.0.8
    depends_on:
      - shakal_bot_db

  async_task_manager:
    image: async_task_manager-image
    container_name: async_task_manager
    profiles:
      - include
    build:
      context: ./
      dockerfile: docker/asyncTaskManagerDockerfile
    volumes:
      - manager_vol:/async-manager
    restart: always
    networks:
      internal_network:
        ipv4_address: 172.24.0.9

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/telegram-data/database
  
  bot_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/telegram-data/bot-files

  manager_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/telegram-data/async-manager

networks:
  shakal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1

  internal_network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
