version: "3.8"

services:
  shakal_bot_db:
    image: shakal-bot-db-image
    container_name: shakal-bot-db
    build:
      context: ./SHAKAL-BOT
      dockerfile: ./docker/dbDockerfile
    environment:
      - DB_NAME=${SHAKAL_BOT_DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_vol:/var/lib/postgresql/data
    restart: always
    networks:
     shakal_network:
       ipv4_address: 172.23.0.2

  shakal_bot_service:
    image: shakal-bot-docker-image
    container_name: shakal-bot-service
    build:
      context: ./SHAKAL-BOT
      dockerfile: ./docker/serviceDockerfile
      args:
        - SHAKAL_BOT_TOKEN=${SHAKAL_BOT_TOKEN}
        - SHAKAL_BOT_LOG_FILE=${SHAKAL_BOT_LOG_FILE}
    env_file:
      - .env
    volumes:
      - bot_vol:/bot-files
    networks:
      shakal_network:
        ipv4_address: 172.23.0.3
    depends_on:
      - shakal_bot_db

  water_stuff_bot_service:
    image: water-stuff-bot-image
    container_name: water-stuff-bot-service
    build:
      context: ./WATER-STUFF-BOT
      dockerfile: ./docker/serviceDockerfile
      args:
        - WATER_STUFF_BOT_TOKEN=${WATER_STUFF_BOT_TOKEN}
        - WATER_STUFF_BOT_LOG_FILE=${WATER_STUFF_BOT_LOG_FILE}
        - WATER_STUFF_BOT_WORKING_FILE=${WATER_STUFF_BOT_WORKING_FILE}
        - WATER_STUFF_BOT_USERNAME=${WATER_STUFF_BOT_USERNAME}
        - WATER_STUFF_BOT_CHAT_ID=${WATER_STUFF_BOT_CHAT_ID}
    env_file:
      - .env
    volumes:
      - bot_vol:/bot-files
    depends_on:
      - shakal_bot_service

  chat_gpt_bot_service:
    image: chat-gpt-bot-image
    container_name: chat-gpt-bot-service
    build:
      context: ./CHAT-GPT-BOT
      dockerfile: ./docker/serviceDockerfile
      args:
        - CHAT_GPT_BOT_TOKEN=${CHAT_GPT_BOT_TOKEN}
        - CHAT_GPT_API_TOKEN=${CHAT_GPT_API_TOKEN}
        - CHAT_GPT_LOG_FILE=${CHAT_GPT_LOG_FILE}
        - CHAT_GPT_USERNAME=${CHAT_GPT_USERNAME}
        - CHAT_GPT_CHAT_ID=${CHAT_GPT_CHAT_ID}
    env_file:
      - .env
    volumes:
      - bot_vol:/bot-files
    depends_on:
      - water_stuff_bot_service

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/SHAKAL-BOT/db-volume
  
  bot_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/SHAKAL-BOT/bot-volume

networks:
  shakal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
