spring:
  application:
    name: ${rocketchat.telegram-bot.spring.application.name}
  datasource:
    url: ${common.db.url}
    driver-class-name: ${common.db.driver.name}
    hikari:
      username: ${common.db.username}
      password: ${common.db.password}
      data-source-properties:
        ssl: ${common.db.ssl}
        sslmode: ${common.db.sslmode}
        sslcert: ${rocketchat.telegram-bot.spring.datasource.hikari.data-source-properties.sslcert}
        sslkey: ${rocketchat.telegram-bot.spring.datasource.hikari.data-source-properties.sslkey}
        sslrootcert: ${rocketchat.telegram-bot.spring.datasource.hikari.data-source-properties.sslrootcert}
  ssl:
    bundle:
      jks:
        rocketchat-telegram-bot-server:
          key:
            alias: ${rocketchat.telegram-bot.spring.ssl.bundle.jks.telegram-bot.key.alias}
          keystore:
            location: ${rocketchat.telegram-bot.spring.ssl.bundle.jks.telegram-bot.keystore.location}
            password: ${rocketchat.telegram-bot.spring.ssl.bundle.jks.telegram-bot.keystore.password}
          truststore:
            location: ${rocketchat.telegram-bot.spring.ssl.bundle.jks.telegram-bot.truststore.location}
            password: ${rocketchat.telegram-bot.spring.ssl.bundle.jks.telegram-bot.truststore.password}
server:
  port: ${rocketchat.telegram-bot.server.port}
  ssl:
    bundle: ${rocketchat.telegram-bot.server.ssl.bundle}
    enabled: ${rocketchat.telegram-bot.server.ssl.enabled}
    client-auth: ${rocketchat.telegram-bot.server.ssl.client-auth}
crypto:
  password: ${rocketchat.telegram-bot.crypto.password}
  salt: ${rocketchat.telegram-bot.crypto.salt}
management:
  endpoints:
    web:
      exposure:
        include: ${rocketchat.telegram-bot.management.endpoints.web.exposure.include}
  server:
    port: ${rocketchat.telegram-bot.management.server.port}
    ssl:
      enabled: ${rocketchat.telegram-bot.management.server.ssl.enabled}
websocket:
  client:
    url: ${rocketchat.telegram-bot.websocket.client.url}
cache:
  data-cache:
    property-name: ${rocketchat.telegram-bot.cache.data-cache.property-name}
  auth-cache:
    property-name: ${rocketchat.telegram-bot.cache.auth-cache.property-name}
service:
  commands:
    commands-list:
      qr: ${rocketchat.telegram-bot.service.commands.commands-list.qr}
    commands-to-proxy:
      - name: ${rocketchat.telegram-bot.service.commands.commands-to-proxy.name.1}
        timeout-sec: ${rocketchat.telegram-bot.service.commands.commands-to-proxy.timeout-sec.1}
  output-directory: ${rocketchat.telegram-bot.service.output-directory}
pms:
  client:
    http-client:
      ssl-bundle-name: ${rocketchat.pms.client.http-client.ssl-bundle-name}
      url:
        base: ${rocketchat.pms.client.http-client.url.base}
      endpoint:
        get-parameter: ${rocketchat.pms.client.http-client.endpoint.get-parameter}
        get-all-parameters: ${rocketchat.pms.client.http-client.endpoint.get-all-parameters}
        register-parameters: ${rocketchat.pms.client.http-client.endpoint.register-parameters}
        update-parameter: ${rocketchat.pms.client.http-client.endpoint.update-parameter}
telegram-bot:
  token: ${rocketchat.telegram-bot.telegram-bot.token}
logging:
  file:
    name: ${rocketchat.telegram-bot.logging.file.name}
