spring:
  ssl:
    bundle:
      jks:
        telegram-bot:
          key:
            alias: ${water-stuff.telegram-bot.spring.ssl.bundle.jks.telegram-bot.key.alias}
          keystore:
            location: ${water-stuff.telegram-bot.spring.ssl.bundle.jks.telegram-bot.keystore.location}
            password: ${water-stuff.telegram-bot.spring.ssl.bundle.jks.telegram-bot.keystore.password}
          truststore:
            location: ${water-stuff.telegram-bot.spring.ssl.bundle.jks.telegram-bot.truststore.location}
            password: ${water-stuff.telegram-bot.spring.ssl.bundle.jks.telegram-bot.truststore.password}
server:
  port: ${water-stuff.telegram-bot.server.port}
  ssl:
    bundle: ${water-stuff.telegram-bot.server.ssl.bundle}
    enabled: ${water-stuff.telegram-bot.server.ssl.enabled}
    client-auth: ${water-stuff.telegram-bot.server.ssl.client-auth}
telegram-bot:
  token: ${water-stuff.telegram-bot.telegram-bot.token}
reminder:
  sleep-time: ${water-stuff.telegram-bot.reminder.sleep-time}
service:
  url: ${water-stuff.telegram-bot.service.url}
  endpoint:
    waterStuffServiceRequest: ${water-stuff.telegram-bot.service.endpoint.waterStuffServiceRequest}
    reminderServiceRequest: ${water-stuff.telegram-bot.service.endpoint.reminderServiceRequest}
logging:
  file:
    name: ${water-stuff.telegram-bot.logging.file.name}
  logback:
    rollingpolicy:
      max-file-size: ${water-stuff.telegram-bot.logging.logback.rollingpolicy.max-file-size}
