version: "3.8"

services:
  water_stuff_telegram_bot:
    image: ${WATER_STUFF_TELEGRAM_BOT_IMAGE}:${TAG:-latest}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: ${WATER_STUFF_TELEGRAM_BOT_LIMITS_CPU}
          memory: ${WATER_STUFF_TELEGRAM_BOT_LIMITS_MEM}
        reservations:
          cpus: ${WATER_STUFF_TELEGRAM_BOT_REQ_CPU}
          memory: ${WATER_STUFF_TELEGRAM_BOT_REQ_MEM}
    stop_grace_period: 60s
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8080/actuator/health || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 48
    env_file:
      - .env
    networks:
      cluster_network:
        aliases:
          - water-stuff-telegram-bot
    volumes:
      - ${NFS}/services/telegram-bot/volumes/water-stuff-telegram-bot:/volumes/water-stuff-telegram-bot
    logging:
      driver: "json-file"
      options:
        max-size: "15m"
        max-file: 1

networks:
  cluster_network:
    external: true
    name: ${CLUSTER_NETWORK}
