spring:
  application:
    name: ${monitoring.telegram-bot.spring.application.name}
  datasource:
    url: ${common.db.url}
    driver-class-name: ${common.db.driver.name}
    hikari:
      username: ${common.db.username}
      password: ${common.db.password}
      data-source-properties:
        ssl: ${common.db.ssl}
        sslmode: ${common.db.sslmode}
        sslcert: ${monitoring.telegram-bot.spring.datasource.hikari.data-source-properties.sslcert}
        sslkey: ${monitoring.telegram-bot.spring.datasource.hikari.data-source-properties.sslkey}
        sslrootcert: ${monitoring.telegram-bot.spring.datasource.hikari.data-source-properties.sslrootcert}
  ssl:
    bundle:
      jks:
        monitoring-telegram-bot-server:
          key:
            alias: ${monitoring.telegram-bot.spring.ssl.bundle.jks.telegram-bot.key.alias}
          keystore:
            location: ${monitoring.telegram-bot.spring.ssl.bundle.jks.telegram-bot.keystore.location}
            password: ${monitoring.telegram-bot.spring.ssl.bundle.jks.telegram-bot.keystore.password}
          truststore:
            location: ${monitoring.telegram-bot.spring.ssl.bundle.jks.telegram-bot.truststore.location}
            password: ${monitoring.telegram-bot.spring.ssl.bundle.jks.telegram-bot.truststore.password}
server:
  port: ${monitoring.telegram-bot.server.port}
  ssl:
    bundle: ${monitoring.telegram-bot.server.ssl.bundle}
    client-auth: ${monitoring.telegram-bot.server.ssl.client-auth}
    enabled: ${monitoring.telegram-bot.server.ssl.enabled}
management:
  endpoints:
    web:
      exposure:
        include: ${monitoring.telegram-bot.management.endpoints.web.exposure.include}
cache:
  data-cache:
    property-name: ${monitoring.telegram-bot.cache.data-cache.property-name}
  auth-cache:
    property-name: ${monitoring.telegram-bot.cache.auth-cache.property-name}
constants-handler:
  working-file: ${monitoring.telegram-bot.constants-handler.working-file}
async-task-service:
  working-file: ${monitoring.telegram-bot.async-task-service.working-file}
crypto:
  password: ${monitoring.telegram-bot.crypto.password}
  salt: ${monitoring.telegram-bot.crypto.salt}
certificates:
  ca:
    cert-path: ${monitoring.telegram-bot.certificates.ca.cert-path}
    key-path: ${monitoring.telegram-bot.certificates.ca.key-path}
  issuer:
    prefix: ${monitoring.telegram-bot.certificates.issuer.prefix}
    ca-common-name: ${monitoring.telegram-bot.certificates.issuer.ca-common-name}
  output-directory: ${monitoring.telegram-bot.certificates.output-directory}
pms:
  client:
    http-client:
      ssl-bundle-name: ${monitoring.pms.client.http-client.ssl-bundle-name}
      url:
        base: ${monitoring.pms.client.http-client.url.base}
      endpoint:
        get-parameter: ${monitoring.pms.client.http-client.endpoint.get-parameter}
        get-all-parameters: ${monitoring.pms.client.http-client.endpoint.get-all-parameters}
        register-parameters: ${monitoring.pms.client.http-client.endpoint.register-parameters}
        update-parameter: ${monitoring.pms.client.http-client.endpoint.update-parameter}
telegram-bot:
  token: ${monitoring.telegram-bot.telegram-bot.token}
  task-target: ${monitoring.telegram-bot.telegram-bot.task-target}
logging:
  file:
    name: ${monitoring.telegram-bot.logging.file.name}
