spring:
  ssl:
    bundle:
      jks:
        telegram-bot:
          key:
            alias: ${monitoring.telegram-bot.spring.ssl.bundle.jks.telegram-bot.key.alias}
          keystore:
            location: ${monitoring.telegram-bot.spring.ssl.bundle.jks.telegram-bot.keystore.location}
            password: ${monitoring.telegram-bot.spring.ssl.bundle.jks.telegram-bot.keystore.password}
          truststore:
            location: ${monitoring.telegram-bot.spring.ssl.bundle.jks.telegram-bot.truststore.location}
            password: ${monitoring.telegram-bot.spring.ssl.bundle.jks.telegram-bot.truststore.password}
server:
  port: ${monitoring.telegram-bot.server.port}
  ssl:
    bundle: ${monitoring.telegram-bot.server.ssl.bundle}
    client-auth: ${monitoring.telegram-bot.server.ssl.client-auth}
    enabled: ${monitoring.telegram-bot.server.ssl.enabled}
telegram-bot:
  token: ${monitoring.telegram-bot.telegram-bot.token}
  task-target: ${monitoring.telegram-bot.telegram-bot.task-target}
service:
  url: ${monitoring.telegram-bot.service.url}
  endpoint:
    monitoringServiceRequest: ${monitoring.telegram-bot.service.endpoint.monitoringServiceRequest}
logging:
  file:
    name: ${monitoring.telegram-bot.logging.file.name}
  logback:
    rollingpolicy:
      max-file-size: ${monitoring.telegram-bot.logging.logback.rollingpolicy.max-file-size}